services:
  db:
    container_name: postgresCont
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    restart: always
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@admin.org"
      PGADMIN_DEFAULT_PASSWORD: "test@admin.org"
    depends_on:
      - db
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
volumes:
  pgdata:
  pgadmin-data: